### ISSUE TITLE
Review Tampilan

### ISSUE THREAD

**Issue by dedeanggara08** [siVarioPutih/koperasi-ibbs-laravel#2]
saldo di daftar santri seharusnya ditambahkan currency format laravel contoh Rp.20.000

**Comment by dedeanggaraxlrplb** [comment]
![Uploading Screenshot 2024-05-11 at 15.25.23.png…]()

**Comment by dedeanggaraxlrplb** [comment]
![Uploading Screenshot 2024-05-11 at 15.25.23.png…]()

**Comment by siVarioPutih** [comment]
noted

**Comment by dedeanggaraxlrplb** [comment]
if (!function_exists('currency_IDR')) {
  function currency_IDR($value)
  {
    try {
      // return number_format($value, 0, ',', '.');
      $value = str_replace(',', '', $value);
      $decimal = 0;
      if (strpos($value, '.') !== false) {
        $decimal = 2;
      }
      return number_format($value, $decimal, '.', ',');
    } catch (\Throwable $th) {
      return $value;
    }
  }
}

**Comment by dedeanggaraxlrplb** [comment]
function terbilang($angka)
{
  $bilangan = array(
    '',
    'satu',
    'dua',
    'tiga',
    'empat',
    'lima',
    'enam',
    'tujuh',
    'delapan',
    'sembilan',
    'sepuluh',
    'sebelas'
  );
  $angka = trim($angka);
  if ($angka < 12) {
    return $bilangan[$angka];
  } elseif ($angka < 20) {
    return $bilangan[$angka - 10] . ' belas';
  } elseif ($angka < 100) {
    $hasil = trim(terbilang($angka % 10));
    return terbilang(floor($angka / 10)) . ' puluh ' . $hasil;
  } elseif ($angka < 200) {
    $hasil = trim(terbilang($angka % 100));
    return 'seratus ' . $hasil;
  } elseif ($angka < 1000) {
    $hasil = trim(terbilang($angka % 100));
    return terbilang(floor($angka / 100)) . ' ratus ' . $hasil;
  } elseif ($angka < 2000) {
    $hasil = trim(terbilang($angka % 1000));
    return 'seribu ' . $hasil;
  } elseif ($angka < 1000000) {
    $hasil = trim(terbilang($angka % 1000));
    return terbilang(floor($angka / 1000)) . ' ribu ' . $hasil;
  } elseif ($angka < 1000000000) {
    $hasil = trim(terbilang($angka % 1000000));
    return terbilang(floor($angka / 1000000)) . ' juta ' . $hasil;
  } elseif ($angka < 1000000000000) {
    $hasil = trim(terbilang($angka % 1000000000));
    return terbilang(floor($angka / 1000000000)) . ' milyar ' . $hasil;
  } elseif ($angka < 1000000000000000) {
    $hasil = trim(terbilang($angka % 1000000000000));
    return terbilang(floor($angka / 1000000000000)) . ' trilyun ' . $hasil;
  } else {
    return 'undefined';
  }
}
