### ISSUE TITLE
Laporan

### ISSUE THREAD

**Issue by FelixItsMe** [siVarioPutih/koperasi-ibbs-laravel#3]
Dalam laporan, untuk saldo ditambahkan format mata uang rupiah. Contoh: Rp 5.000,00
![screenshot-1715415877412](https://github.com/siVarioPutih/koperasi-ibbs-laravel/assets/49501836/b3b0c8b3-87ce-4bdb-9168-03f1b2b2f0e3)

**Comment by siVarioPutih** [comment]
noted
